# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  workingDirectory: '.'
  solution: './**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  solutionFolder: '$(workingDirectory)'
  clientProjectDirectory: '$(workingDirectory)\\SimbaToursEastAfrica'
  targetDeployDirectory: '$(build.artifactStagingDirectory)'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: Npm@1
  inputs:  
    command: 'install'
    workingDir: '$(clientProjectDirectory)'
    customCommand: 'npm ng build'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(clientProjectDirectory)\\ClientApp'
    Contents: '**/*.js'
    TargetFolder: '$(targetDeployDirectory)\\dist'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(clientProjectDirectory)\\wwwroot'
    Contents: '**'
    TargetFolder: '$(targetDeployDirectory)'
